[toolchain]
package_manager = "npm"

[features]
resolution = false
skip-lint = false

[programs.localnet]
grindurus = "14YUdGTp3Qk2KbFpus8MV2d4hC5Ks3dvwy9mJbH4Bv7k"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npx tsx ./node_modules/mocha/bin/mocha -t 1000000 tests/**/*.ts"
